export const WRESTLING_NAMES = [
  "Tombstone",
  "Piledriver",
  "Powerbomb",
  "Stunner",
  "Sharpshooter",
  "Crossface",
  "Pedigree",
  "Swanton",
  "Lionsault",
  "Codebreaker",
  "Hurricanrana",
  "Moonsault",
  "Brainbuster",
  "Spear",
  "Chokeslam",
  "Anklelock",
  "FigureFour",
  "Crossbody",
  "FrogSplash",
  "ShootingStar",
  "Destroyer",
  "Lariatoo",
  "ElbowDrop",
  "RockBottom",
  "PoisonRana",
  "Dragonrana",
  "Vertebreaker",
  "BurningHammer",
  "TigerDriver",
  "CattleMutilation",
  "RollingElbow",
  "Frankensteiner",
  "GermanSuplex",
  "TigerSuplex",
  "DiamondCutter",
  "Uranage",
  "Backbreaker",
  "SwantonBomb",
  "PerfectPlex",
  "Headscissors",
  "FlyingElbow",
  "CurbStomp",
  "Killswitch",
  "Mandible",
  "Superkick",
  "Cradle",
  "Neckbreaker",
  "Springboard",
  "Whiplash",
  "Facebuster",
] as const;

export function randomWrestlingName(): string {
  return WRESTLING_NAMES[Math.floor(Math.random() * WRESTLING_NAMES.length)];
}
